eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 10

spring:
  zipkin:
    base-url: http://zipkin:9411/api/v2/spans
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authService
                fallbackUri: forward:/fallback
                statusCodes:
                  - INTERNAL_SERVER_ERROR
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
        - id: books
          uri: lb://book-service
          predicates:
            - Path=/books/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationService
                fallbackUri: forward:/fallback
                statusCodes:
                  - INTERNAL_SERVER_ERROR
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE

  main:
    web-application-type: reactive

resilience4j:
  circuitbreaker:
    instances:
      authService:
        slidingWindowSize: 10                     #For every last 10 requests will be examined in Closed state.
        permittedNumberOfCallsInHalfOpenState: 10  #In Half Open state, we allow 10 requests that will be examined to see if the situation changes.
        failureRateThreshold: 50                  #If the 50 percent of last requests are failure, the circuit will change to Open.
        waitDurationInOpenState: 10000            #The circuit becomes Half Open after 10 seconds.
        registerHealthIndicator: true
      notificationService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 10
        failureRateThreshold: 20
        waitDurationInOpenState: 1000
        registerHealthIndicator: true
      profileService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 10
        failureRateThreshold: 20
        waitDurationInOpenState: 120000
        registerHealthIndicator: true
      merchantService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 10
        failureRateThreshold: 10
        waitDurationInOpenState: 10000
        registerHealthIndicator: true
      scoringService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 10
        failureRateThreshold: 10
        waitDurationInOpenState: 10000
        registerHealthIndicator: true

  timelimiter:
    instances:
      authService:
        timeoutDuration: 30s #We want the users experience fast request, fast system. So we set a timeout. If the request takes more than 2s, it will be returned. No long wait.
      notificationService:
        timeoutDuration: 10s
      profileService:
        timeoutDuration: 10s
      merchantService:
        timeoutDuration: 120s
      scoringService:
        timeoutDuration: 120s


logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: warn
    org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager: WARN
    org.apache.hc.client5.http.impl.classic.InternalHttpClient: WARN


#This part only for Logging to Loki

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
logs:
  application:
    loki:
      base-url: http://loki:3100

#End of  part only for Logging to Loki
